AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  doc-store

  SAM Template for JSON document database
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DocStoreFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: doc-store/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetDocument:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        AddDocument:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "doc-store-documents"
      VersioningConfiguration:
        Status: "Enabled"
  # Give access for Lambda to access the S3 bucket
  DocumentBucketPolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: "DocumentBucketAccess"
      RoleName: !Ref DocStoreFunctionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DocumentBucket
                - /*

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DocStoreApi:
    Description: "API Gateway endpoint URL for Prod stage for Document Storage function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  DocStoreFunction:
    Description: "Document Storage Lambda Function ARN"
    Value: !GetAtt DocStoreFunction.Arn
  DocStoreFunctionIamRole:
    Description: "Implicit IAM Role created for Document Storage function"
    Value: !GetAtt DocStoreFunctionRole.Arn
